import type { FirebaseOptions } from 'firebase/app';

// This file was generated by an AI tool.
// It is recommended to review and commit this file to your source control.
// This file is not sourced from environment variables, so it does not require environment variables to be set.

export const firebaseConfig: FirebaseOptions = {
  "projectId": "vincent-designs",
  "appId": "1:201595097998:web:812ffdc2480d00488a0adf",
  "apiKey": "AIzaSyDsWjvw_MGdM0sk7quTLKUTxRmdjVOXVoE",
  "authDomain": "vincent-designs.firebaseapp.com",
  "storageBucket": "vincent-designs.appspot.com",
  "measurementId": "G-84PDSFHYSK",
  "messagingSenderId": "201595097998"
};
